apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - path: patch-cronjob.yaml
images:
  - name: ghcr.io/example/email-assistant
    newName: ghcr.io/okeyobia/email_assistant
    newTag: 1ab0bc757834b9fbcdb46ef5b0ddc532b7a83b75
